name: k6 Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6_test:
    name: Peformance Tests with k6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Runs login test
      - name: Create dummy Payloads file
        run: |
          mkdir -p data
          echo 'export const PAYLOADS = { login: { "email": __ENV.USER_EMAIL, "password": __ENV.USER_PASSWORD }, post_testimonial: { "title": "", "content": "", "rating": 5, "isPublic": true }, update_testimonial: { "title": "", "content": "", "rating": 5 } };' > data/Payloads.js

      - name: Run k6 login test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/loginTest.js
          flags: >
            --env USER_EMAIL=${{ secrets.EMAIL }} 
            --env USER_PASSWORD=${{ secrets.PASSWORD }}

      - name: Run k6 getProfile Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/getProfileTest.js
          flags: >
            --env USER_EMAIL=${{ secrets.EMAIL }}
            --env USER_PASSWORD=${{ secrets.PASSWORD }}

      - name: Run k6 Post Testimonial Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/postTestimonialTest.js
          flags: >
            --env USER_EMAIL=${{ secrets.EMAIL }}
            --env USER_PASSWORD=${{ secrets.PASSWORD }}